### ISSUE TITLE
PHP SDK Request.php

### ISSUE THREAD

**Issue by Stacey940** [passworks/passworks-php#2]
I think there is some problem with the response sent in the Request.php file in PHP SDK.

It is not returning the stdClass Object. If you are doing this:

$api = new Passworks\Client('username', 'key', true);
$icon = $api->createAsset('icon', 'full_path_of_file/crown.png');
var_dump($icon);

it will return NULL.

To return the object with the ids and other information for any of the Request made , we need to change this request function in Request.php

public function request($method, $url, $post_data=null, $headers=null)

I have modified below code and now its returning the stdClass Object

   //my code
    
    $header_size = curl_getinfo($curl, CURLINFO_HEADER_SIZE);
    $header = substr($result, 0, $header_size);
    $body = substr($result, $header_size);
    
    //mycode ends
    
    curl_close($curl);
    
   return json_decode($body);
Please check if its only me who was facing that issue or the SDK needs the Request.php corrected.

My Current PHP version is : 5.6.32

Thanks

**Comment by lmmendes** [comment]
From my findings, the issue seems to be related to the server issuing a  `100 Continue` HTTP code before sending the "real" result during some uploads.

Example request:

```
POST /v2/assets/ HTTP/1.1
Host: api.passworks.io
Accept: */*
Content-Length: 429
Expect: 100-continue
Content-Type: multipart/form-data
```

Example response:

```
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Mon, 18 Dec 2017 19:01:00 GMT
Server: nginx
Vary: Accept-Encoding,User-Agent
Content-Length: 256
Content-Type: application/json; charset=utf-8
```

The solution would be to ignore the `100 Continue` response if we receive it.

**Comment by Stacey940** [comment]
Thanks. Solved
